[2023-11-05T12:13:44.238+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_names.streaming_to_kafka manual__2023-11-05T12:11:56.445773+00:00 [queued]>
[2023-11-05T12:13:44.250+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_names.streaming_to_kafka manual__2023-11-05T12:11:56.445773+00:00 [queued]>
[2023-11-05T12:13:44.250+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-05T12:13:44.486+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): streaming_to_kafka> on 2023-11-05 12:11:56.445773+00:00
[2023-11-05T12:13:44.501+0000] {standard_task_runner.py:57} INFO - Started process 242 to run task
[2023-11-05T12:13:44.507+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'random_names', 'streaming_to_kafka', 'manual__2023-11-05T12:11:56.445773+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6kkc8hjg']
[2023-11-05T12:13:44.513+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask streaming_to_kafka
[2023-11-05T12:13:45.719+0000] {task_command.py:415} INFO - Running <TaskInstance: random_names.streaming_to_kafka manual__2023-11-05T12:11:56.445773+00:00 [running]> on host c5850c66cc50
[2023-11-05T12:13:56.286+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='random_names' AIRFLOW_CTX_TASK_ID='streaming_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T12:11:56.445773+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T12:11:56.445773+00:00'
[2023-11-05T12:14:14.837+0000] {logging_mixin.py:151} INFO - {'full name': 'Mr Justus Janke', 'gender': 'male', 'location': 'Fasanenweg 2935', 'city': 'Bad Oldesloe', 'country': 'Germany', 'postcode': 36357, 'latitude': '-53.2909', 'longtitude': '-173.3705', 'email': 'justus.janke@example.com'}
[2023-11-05T12:14:15.952+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: connecting to kafka:9092 [('172.22.0.7', 9092) IPv4]
[2023-11-05T12:14:15.954+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-11-05T12:14:16.226+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: Connection complete.
[2023-11-05T12:14:18.326+0000] {conn.py:1055} WARNING - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.22.0.7', 9092)]> timed out after 1415.268898010254 ms. Closing connection.
[2023-11-05T12:14:18.327+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.22.0.7', 9092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 1415.268898010254 ms
[2023-11-05T12:14:18.988+0000] {conn.py:1293} INFO - Broker is not v(0, 10) -- it did not recognize ApiVersionRequest_v0
[2023-11-05T12:14:20.679+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/script.py", line 50, in start_streaming
    producer = get_kafka_producer()
  File "/opt/airflow/dags/scripts/script.py", line 31, in get_kafka_producer
    producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-11-05T12:14:48.744+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 136 for task streaming_to_kafka ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 242)
[2023-11-05T12:15:08.927+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T12:15:20.624+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
