[2023-11-05T12:13:44.234+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_names.streaming_to_kafka scheduled__2023-11-05T12:05:00+00:00 [queued]>
[2023-11-05T12:13:44.247+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_names.streaming_to_kafka scheduled__2023-11-05T12:05:00+00:00 [queued]>
[2023-11-05T12:13:44.247+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-05T12:13:44.364+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): streaming_to_kafka> on 2023-11-05 12:05:00+00:00
[2023-11-05T12:13:44.378+0000] {standard_task_runner.py:57} INFO - Started process 241 to run task
[2023-11-05T12:13:44.388+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'random_names', 'streaming_to_kafka', 'scheduled__2023-11-05T12:05:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp14mlbv6u']
[2023-11-05T12:13:44.392+0000] {standard_task_runner.py:85} INFO - Job 137: Subtask streaming_to_kafka
[2023-11-05T12:13:45.497+0000] {task_command.py:415} INFO - Running <TaskInstance: random_names.streaming_to_kafka scheduled__2023-11-05T12:05:00+00:00 [running]> on host c5850c66cc50
[2023-11-05T12:13:56.288+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='random_names' AIRFLOW_CTX_TASK_ID='streaming_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T12:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-05T12:05:00+00:00'
[2023-11-05T12:14:14.838+0000] {logging_mixin.py:151} INFO - {'full name': 'Ms Sonya Govorun', 'gender': 'female', 'location': 'Frometivskiy uzviz 461', 'city': 'Novodnistrovsk', 'country': 'Ukraine', 'postcode': 13451, 'latitude': '81.1333', 'longtitude': '15.4713', 'email': 'sonya.govorun@example.com'}
[2023-11-05T12:14:15.952+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: connecting to kafka:9092 [('172.22.0.7', 9092) IPv4]
[2023-11-05T12:14:15.954+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-11-05T12:14:16.226+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: Connection complete.
[2023-11-05T12:14:18.532+0000] {conn.py:1055} WARNING - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.22.0.7', 9092)]> timed out after 1427.100658416748 ms. Closing connection.
[2023-11-05T12:14:18.533+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.22.0.7', 9092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 1427.100658416748 ms
[2023-11-05T12:14:18.988+0000] {conn.py:1293} INFO - Broker is not v(0, 10) -- it did not recognize ApiVersionRequest_v0
[2023-11-05T12:14:20.679+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/script.py", line 50, in start_streaming
    producer = get_kafka_producer()
  File "/opt/airflow/dags/scripts/script.py", line 31, in get_kafka_producer
    producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-11-05T12:14:48.744+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 137 for task streaming_to_kafka ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 241)
[2023-11-05T12:15:08.923+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T12:15:20.623+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
